export const countries = [
  { name: "Afghanistan", phoneCode: "+93", flag: "🇦🇫" },
  { name: "Albania", phoneCode: "+355", flag: "🇦🇱" },
  { name: "Algeria", phoneCode: "+213", flag: "🇩🇿" },
  { name: "Andorra", phoneCode: "+376", flag: "🇦🇩" },
  { name: "Angola", phoneCode: "+244", flag: "🇦🇴" },
  { name: "Antigua and Barbuda", phoneCode: "+1-268", flag: "🇦🇬" },
  { name: "Argentina", phoneCode: "+54", flag: "🇦🇷" },
  { name: "Armenia", phoneCode: "+374", flag: "🇦🇲" },
  { name: "Australia", phoneCode: "+61", flag: "🇦🇺" },
  { name: "Austria", phoneCode: "+43", flag: "🇦🇹" },
  { name: "Azerbaijan", phoneCode: "+994", flag: "🇦🇿" },
  { name: "Bahamas", phoneCode: "+1-242", flag: "🇧🇸" },
  { name: "Bahrain", phoneCode: "+973", flag: "🇧🇭" },
  { name: "Bangladesh", phoneCode: "+880", flag: "🇧🇩" },
  { name: "Barbados", phoneCode: "+1-246", flag: "🇧🇧" },
  { name: "Belarus", phoneCode: "+375", flag: "🇧🇾" },
  { name: "Belgium", phoneCode: "+32", flag: "🇧🇪" },
  { name: "Belize", phoneCode: "+501", flag: "🇧🇿" },
  { name: "Benin", phoneCode: "+229", flag: "🇧🇯" },
  { name: "Bhutan", phoneCode: "+975", flag: "🇧🇹" },
  { name: "Bolivia", phoneCode: "+591", flag: "🇧🇴" },
  { name: "Bosnia and Herzegovina", phoneCode: "+387", flag: "🇧🇦" },
  { name: "Botswana", phoneCode: "+267", flag: "🇧🇼" },
  { name: "Brazil", phoneCode: "+55", flag: "🇧🇷" },
  { name: "Brunei", phoneCode: "+673", flag: "🇧🇳" },
  { name: "Bulgaria", phoneCode: "+359", flag: "🇧🇬" },
  { name: "Burkina Faso", phoneCode: "+226", flag: "🇧🇫" },
  { name: "Burundi", phoneCode: "+257", flag: "🇧🇮" },
  { name: "Cabo Verde", phoneCode: "+238", flag: "🇨🇻" },
  { name: "Cambodia", phoneCode: "+855", flag: "🇰🇭" },
  { name: "Cameroon", phoneCode: "+237", flag: "🇨🇲" },
  { name: "Canada", phoneCode: "+1", flag: "🇨🇦" },
  { name: "Central African Republic", phoneCode: "+236", flag: "🇨🇫" },
  { name: "Chad", phoneCode: "+235", flag: "🇹🇩" },
  { name: "Chile", phoneCode: "+56", flag: "🇨🇱" },
  { name: "China", phoneCode: "+86", flag: "🇨🇳" },
  { name: "Colombia", phoneCode: "+57", flag: "🇨🇴" },
  { name: "Comoros", phoneCode: "+269", flag: "🇰🇲" },
  { name: "Congo, Democratic Republic of the", phoneCode: "+243", flag: "🇨🇩" },
  { name: "Congo, Republic of the", phoneCode: "+242", flag: "🇨🇬" },
  { name: "Costa Rica", phoneCode: "+506", flag: "🇨🇷" },
  { name: "Croatia", phoneCode: "+385", flag: "🇭🇷" },
  { name: "Cuba", phoneCode: "+53", flag: "🇨🇺" },
  { name: "Cyprus", phoneCode: "+357", flag: "🇨🇾" },
  { name: "Czech Republic", phoneCode: "+420", flag: "🇨🇿" },
  { name: "Denmark", phoneCode: "+45", flag: "🇩🇰" },
  { name: "Djibouti", phoneCode: "+253", flag: "🇩🇯" },
  { name: "Dominica", phoneCode: "+1-767", flag: "🇩🇲" },
  { name: "Dominican Republic", phoneCode: "+1-809", flag: "🇩🇴" },
  { name: "Ecuador", phoneCode: "+593", flag: "🇪🇨" },
  { name: "Egypt", phoneCode: "+20", flag: "🇪🇬" },
  { name: "El Salvador", phoneCode: "+503", flag: "🇸🇻" },
  { name: "Equatorial Guinea", phoneCode: "+240", flag: "🇬🇶" },
  { name: "Eritrea", phoneCode: "+291", flag: "🇪🇷" },
  { name: "Estonia", phoneCode: "+372", flag: "🇪🇪" },
  { name: "Eswatini", phoneCode: "+268", flag: "🇸🇿" },
  { name: "Ethiopia", phoneCode: "+251", flag: "🇪🇹" },
  { name: "Fiji", phoneCode: "+679", flag: "🇫🇯" },
  { name: "Finland", phoneCode: "+358", flag: "🇫🇮" },
  { name: "France", phoneCode: "+33", flag: "🇫🇷" },
  { name: "Gabon", phoneCode: "+241", flag: "🇬🇦" },
  { name: "Gambia", phoneCode: "+220", flag: "🇬🇲" },
  { name: "Georgia", phoneCode: "+995", flag: "🇬🇪" },
  { name: "Germany", phoneCode: "+49", flag: "🇩🇪" },
  { name: "Ghana", phoneCode: "+233", flag: "🇬🇭" },
  { name: "Greece", phoneCode: "+30", flag: "🇬🇷" },
  { name: "Grenada", phoneCode: "+1-473", flag: "🇬🇩" },
  { name: "Guatemala", phoneCode: "+502", flag: "🇬🇹" },
  { name: "Guinea", phoneCode: "+224", flag: "🇬🇳" },
  { name: "Guinea-Bissau", phoneCode: "+245", flag: "🇬🇼" },
  { name: "Guyana", phoneCode: "+592", flag: "🇬🇾" },
  { name: "Haiti", phoneCode: "+509", flag: "🇭🇹" },
  { name: "Honduras", phoneCode: "+504", flag: "🇭🇳" },
  { name: "Hungary", phoneCode: "+36", flag: "🇭🇺" },
  { name: "Iceland", phoneCode: "+354", flag: "🇮🇸" },
  { name: "India", phoneCode: "+91", flag: "🇮🇳" },
  { name: "Indonesia", phoneCode: "+62", flag: "🇮🇩" },
  { name: "Iran", phoneCode: "+98", flag: "🇮🇷" },
  { name: "Iraq", phoneCode: "+964", flag: "🇮🇶" },
  { name: "Ireland", phoneCode: "+353", flag: "🇮🇪" },
  { name: "Israel", phoneCode: "+972", flag: "🇮🇱" },
  { name: "Italy", phoneCode: "+39", flag: "🇮🇹" },
  { name: "JSCP: Jamaica", phoneCode: "+1-876", flag: "🇯🇲" },
  { name: "Japan", phoneCode: "+81", flag: "🇯🇵" },
  { name: "Jordan", phoneCode: "+962", flag: "🇯🇴" },
  { name: "Kazakhstan", phoneCode: "+7", flag: "🇰🇿" },
  { name: "Kenya", phoneCode: "+254", flag: "🇰🇪" },
  { name: "Kiribati", phoneCode: "+686", flag: "🇰🇮" },
  { name: "Korea, North", phoneCode: "+850", flag: "🇰🇵" },
  { name: "Korea, South", phoneCode: "+82", flag: "🇰🇷" },
  { name: "Kuwait", phoneCode: "+965", flag: "🇰🇼" },
  { name: "Kyrgyzstan", phoneCode: "+996", flag: "🇰🇬" },
  { name: "Laos", phoneCode: "+856", flag: "🇱🇦" },
  { name: "Latvia", phoneCode: "+371", flag: "🇱🇻" },
  { name: "Lebanon", phoneCode: "+961", flag: "🇱🇧" },
  { name: "Lesotho", phoneCode: "+266", flag: "🇱🇸" },
  { name: "Liberia", phoneCode: "+231", flag: "🇱🇷" },
  { name: "Libya", phoneCode: "+218", flag: "🇱🇾" },
  { name: "Liechtenstein", phoneCode: "+423", flag: "🇱🇮" },
  { name: "Lithuania", phoneCode: "+370", flag: "🇱🇹" },
  { name: "Luxembourg", phoneCode: "+352", flag: "🇱🇺" },
  { name: "Madagascar", phoneCode: "+261", flag: "🇲🇬" },
  { name: "Malawi", phoneCode: "+265", flag: "🇲🇼" },
  { name: "Malaysia", phoneCode: "+60", flag: "🇲🇾" },
  { name: "Maldives", phoneCode: "+960", flag: "🇲🇻" },
  { name: "Mali", phoneCode: "+223", flag: "🇲🇱" },
  { name: "Malta", phoneCode: "+356", flag: "🇲🇹" },
  { name: "Marshall Islands", phoneCode: "+692", flag: "🇲🇭" },
  { name: "Mauritania", phoneCode: "+222", flag: "🇲🇷" },
  { name: "Mauritius", phoneCode: "+230", flag: "🇲🇺" },
  { name: "Mexico", phoneCode: "+52", flag: "🇲🇽" },
  { name: "Micronesia", phoneCode: "+691", flag: "🇫🇲" },
  { name: "Moldova", phoneCode: "+373", flag: "🇲🇩" },
  { name: "Monaco", phoneCode: "+377", flag: "🇲🇨" },
  { name: "Mongolia", phoneCode: "+976", flag: "🇲🇳" },
  { name: "Montenegro", phoneCode: "+382", flag: "🇲🇪" },
  { name: "Morocco", phoneCode: "+212", flag: "🇲🇦" },
  { name: "Mozambique", phoneCode: "+258", flag: "🇲🇿" },
  { name: "Myanmar", phoneCode: "+95", flag: "🇲🇲" },
  { name: "Namibia", phoneCode: "+264", flag: "🇳🇦" },
  { name: "Nauru", phoneCode: "+674", flag: "🇳🇷" },
  { name: "Nepal", phoneCode: "+977", flag: "🇳🇵" },
  { name: "Netherlands", phoneCode: "+31", flag: "🇳🇱" },
  { name: "New Zealand", phoneCode: "+64", flag: "🇳🇿" },
  { name: "Nicaragua", phoneCode: "+505", flag: "🇳🇮" },
  { name: "Niger", phoneCode: "+227", flag: "🇳🇪" },
  { name: "Nigeria", phoneCode: "+234", flag: "🇳🇬" },
  { name: "North Macedonia", phoneCode: "+389", flag: "🇲🇰" },
  { name: "Norway", phoneCode: "+47", flag: "🇳🇴" },
  { name: "Oman", phoneCode: "+968", flag: "🇴🇲" },
  { name: "Pakistan", phoneCode: "+92", flag: "🇵🇰" },
  { name: "Palau", phoneCode: "+680", flag: "🇵🇼" },
  { name: "Panama", phoneCode: "+507", flag: "🇵🇦" },
  { name: "Papua New Guinea", phoneCode: "+675", flag: "🇵🇬" },
  { name: "Paraguay", phoneCode: "+595", flag: "🇵🇾" },
  { name: "Peru", phoneCode: "+51", flag: "🇵🇪" },
  { name: "Philippines", phoneCode: "+63", flag: "🇵🇭" },
  { name: "Poland", phoneCode: "+48", flag: "🇵🇱" },
  { name: "Portugal", phoneCode: "+351", flag: "🇵🇹" },
  { name: "Qatar", phoneCode: "+974", flag: "🇶🇦" },
  { name: "Romania", phoneCode: "+40", flag: "🇷🇴" },
  { name: "Russia", phoneCode: "+7", flag: "🇷🇺" },
  { name: "Rwanda", phoneCode: "+250", flag: "🇷🇼" },
  { name: "Saint Kitts and Nevis", phoneCode: "+1-869", flag: "🇰🇳" },
  { name: "Saint Lucia", phoneCode: "+1-758", flag: "🇱🇨" },
  { name: "Saint Vincent and the Grenadines", phoneCode: "+1-784", flag: "🇻🇨" },
  { name: "Samoa", phoneCode: "+685", flag: "🇼🇸" },
  { name: "San Marino", phoneCode: "+378", flag: "🇸🇲" },
  { name: "Sao Tome and Principe", phoneCode: "+239", flag: "🇸🇹" },
  { name: "Saudi Arabia", phoneCode: "+966", flag: "🇸🇦" },
  { name: "Senegal", phoneCode: "+221", flag: "🇸🇳" },
  { name: "Serbia", phoneCode: "+381", flag: "🇷🇸" },
  { name: "Seychelles", phoneCode: "+248", flag: "🇸🇨" },
  { name: "Sierra Leone", phoneCode: "+232", flag: "🇸🇱" },
  { name: "Singapore", phoneCode: "+65", flag: "🇸🇬" },
  { name: "Slovakia", phoneCode: "+421", flag: "🇸🇰" },
  { name: "Slovenia", phoneCode: "+386", flag: "🇸🇮" },
  { name: "Solomon Islands", phoneCode: "+677", flag: "🇸🇧" },
  { name: "Somalia", phoneCode: "+252", flag: "🇸🇴" },
  { name: "South Africa", phoneCode: "+27", flag: "🇿🇦" },
  { name: "South Sudan", phoneCode: "+211", flag: "🇸🇸" },
  { name: "Spain", phoneCode: "+34", flag: "🇪🇸" },
  { name: "Sri Lanka", phoneCode: "+94", flag: "🇱🇰" },
  { name: "Sudan", phoneCode: "+249", flag: "🇸🇩" },
  { name: "Suriname", phoneCode: "+597", flag: "🇸🇷" },
  { name: "Sweden", phoneCode: "+46", flag: "🇸🇪" },
  { name: "Switzerland", phoneCode: "+41", flag: "🇨🇭" },
  { name: "Syria", phoneCode: "+963", flag: "🇸🇾" },
  { name: "Taiwan", phoneCode: "+886", flag: "🇹🇼" },
  { name: "Tajikistan", phoneCode: "+992", flag: "🇹🇯" },
  { name: "Tanzania", phoneCode: "+255", flag: "🇹🇿" },
  { name: "Thailand", phoneCode: "+66", flag: "🇹🇭" },
  { name: "Timor-Leste", phoneCode: "+670", flag: "🇹🇱" },
  { name: "Togo", phoneCode: "+228", flag: "🇹🇬" },
  { name: "Tonga", phoneCode: "+676", flag: "🇹🇴" },
  { name: "Trinidad and Tobago", phoneCode: "+1-868", flag: "🇹🇹" },
  { name: "Tunisia", phoneCode: "+216", flag: "🇹🇳" },
  { name: "Turkey", phoneCode: "+90", flag: "🇹🇷" },
  { name: "Turkmenistan", phoneCode: "+993", flag: "🇹🇲" },
  { name: "Tuvalu", phoneCode: "+688", flag: "🇹🇻" },
  { name: "Uganda", phoneCode: "+256", flag: "🇺🇬" },
  { name: "Ukraine", phoneCode: "+380", flag: "🇺🇦" },
  { name: "United Arab Emirates", phoneCode: "+971", flag: "🇦🇪" },
  { name: "United Kingdom", phoneCode: "+44", flag: "🇬🇧" },
  { name: "United States", phoneCode: "+1", flag: "🇺🇸" },
  { name: "Uruguay", phoneCode: "+598", flag: "🇺🇾" },
  { name: "Uzbekistan", phoneCode: "+998", flag: "🇺🇿" },
  { name: "Vanuatu", phoneCode: "+678", flag: "🇻🇺" },
  { name: "Venezuela", phoneCode: "+58", flag: "🇻🇪" },
  { name: "Vietnam", phoneCode: "+84", flag: "🇻🇳" },
  { name: "Yemen", phoneCode: "+967", flag: "🇾🇪" },
  { name: "Zambia", phoneCode: "+260", flag: "🇿🇲" },
  { name: "Zimbabwe", phoneCode: "+263", flag: "🇿🇼" }
];


export const organizationTypes = [
  "International Organizations",
  "Non-Governmental Organizations (NGOs)",
  "Foundations and Associations",
  "Universities and Academic Institutions",
  "Companies and Private Sector Representatives",
  "Public Institutions",
  "Media, Platforms, and Initiatives"
];